### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by rossington19** [rossington19/ByteSizedPuzzle#1]
- [x] ~~Location - Calculate Y values dynamically~~
- [x] ~~Location - Dynamically size buttons~~
- [x] Location - More robust dynamic scaling and layout (boarders?)
- [x] ~~Location - Set Max_Num_Wide dynamically~~
- [x] Rule - Invert
- [x] Rule - 5 (or greater) targets
- [x] Rule - Utilize number of moves not number of buttons for pressing random buttons
-  [x] Rule - Make number of targets a variable number (check if not changes made when % 2 === 0)
- [ ] Rule - Shift (Left, Right, Up and Down)
- [ ] General - Make difficulty selection
- [ ] General - Make some goals and store players results
- [x] ~~Misc - Max number of buttons when rotating set with vars~~
- [x] Misc - Set colors in variable file
